name: Контроль качества

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sonar:
    uses: autumn-library/workflows/.github/workflows/sonar.yml@main
    with:
      github_repository: "%CHANGE_ME%" # Пример: nixel2007/validate
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
